INSERT INTO app_pruebas_recomendaciones (idRecomendacion,detaRecomendacion,preguntas_id,valorNecesario)
VALUES
(0, "Perfecto, sabes utilizar muy bien las tecnologías.", 0, "a"),
(1, "Lo haces bien, pero debes estudiar más sobre las tecnologías y sus respectivos usos.", 0, "m"),
(2, "No fue tan bien, sigue estudiando las tecnologías y su uso.", 0, "b"),
(3, "Perfecto, sabes utilizar muy bien las tecnologías.", 1, "a"),
(4, "Lo haces bien, pero debes practicar para perfeccionar tus habilidades.", 1, "m"),
(5, "Practica el uso de mouse.", 1, "b"),
(6, "Perfecto, eres muy hábil con el mouse.", 2, "a"),
(7, "Lo haces bien, pero debes practicar para perfeccionar tus habilidades.", 2, "m"),
(8, "Practica el uso de mouse.", 2, "b"),
(9, "Perfecto, sabes cómo manejar problemas cotidianos de los aparatos electrónicos.", 3, "a"),
(10, "Lo haces bien, pero estudia más el uso de los aparatos electrónicos", 3,"m"),
(11, "Debes estudiar más sobre el manejo los aparatos electrónicos.", 3, "b"),
(12, "Perfecto,  tienes buenas bases con respecto a tecnologias de comunicacion.", 4, "a"),
(13, "Lo haces bien, pero estudia más las tecnologías de la comunicación.", 4, "m"),
(14, "Debes estudiar más las tecnologías de la comunicación.", 4, "b"),
(15, "Perfecto, asociadas de forma correcta las herramientas con un determinado problema.", 5, "a"),
(16, "Esta bien, pero ejercita tus conocimientos.", 5, "m"),
(17, "esfuérzate por estudiar y practicar el uso de tecnologías y su aplicación.", 5, "b"),
(18, "Perfecto, tienes buenas bases con respecto a tecnologías como facilitador de tareas cotidianas.", 6, "a"),
(19, "Lo haces bien, pero estudia más las tecnologías como un facilitador de tareas.", 6, "m"),
(20, "Debes estudiar más las tecnologías como un facilitador de tareas.", 6, "b"),
(21, "Perfecto, sabes distinguir la utilidad de aparatos electrónicos.", 7, "a"),
(22, "Lo haces bien, pero estudia estudia más cada aparato y su utilidad.", 7, "m"),
(23, "Debes estudiar más los aparatos tecnológicos y su utilidad.", 7, "b"),
(24, "Perfecto, tienes buenas bases con respecto a tecnologías como facilitador de tareas cotidianas.", 8, "a"),
(25, "Lo haces bien, pero estudia más las tecnologías como un facilitador de tareas.", 8, "m"),
(26, "Debes estudiar más las tecnologías como un facilitador de tareas.", 8, "b"),
(27, "Perfecto, sabes cómo actuar frente a situaciones desconocidas.", 9, "a"),
(28, "Tienes idea, pero debes asesorarte mas sobre como actuar en situaciones desconocidas.", 9, "m"),
(29, "Debes asesorarte mas sobre como actuar en situaciones desconocidas.", 9, "b")

